server:
  port: 8084


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
        routes:
         - id: USER-SERVICE
           uri: lb://USER-SERVICE
           predicates:
            - Path=/users/**
         # for more than one url we can use comma sepreated urls
         
         
         - id: HOTEL-SERVICE
           uri: lb://HOTEL-SERVICE
           predicates:
            - Path=/hotels/**
            
         - id: RATING-SERVICE
           uri: lb://RATING-SERVICE
           predicates:
            - Path=/ratings/**



okta:
  oauth2:
    issuer: ############ your issuer id ###############
    audience: api://default
    client-id: ############ your client id ###############
    client-secret: ############ your client secret ###############
    scopes: openid, profile, email, offline_access
