server:
  port: 8082
  
spring:
  application:
    name: HOTEL-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/hotelservice

  config:
    import: optional:configserver:http://localhost:8085/
    
        
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defualtZone: http://localhost:8761/eureka/
      
okta:
  oauth2:
    issuer: ############ your issuer id ###############
    audience: api://default